apiVersion: v1
kind: DeploymentConfig
metadata:
  name: manman-serving
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: manman-serving
    spec:
      containers:
      - name: manman-serving-server
        imagePullPolicy: Always
        image: 172.30.100.208:5000/manman/manman-serving:latest
        ports:
        - containerPort: 8500
        command:
        - bash
        - -c
        - tensorflow_model_server --port=8500 --rest_api_port=8501 --model_name=manman --model_base_path=/app/manman;
        restartPolicy: Always
      - name: manman-serving-client
        image: 172.30.100.208:5000/manman/manman-serving:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        command:
        - bash
        - -c
        - python /app/manman_client_rest_rpc.py --server=localhost:8500 --concurrency=100
        restartPolicy: Always
  triggers:
  - imageChangeParams:
      automatic: true
      containerNames:
      - manman-serving-client
      from:
        kind: ImageStream
        name: manman-serving:latest
    type: ImageChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - manman-serving-server
      from:
        kind: ImageStream
        name: manman-serving:latest
    type: ImageChange
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: manman-serving
  name: manman-serving
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: manman-serving
  type: ClusterIP
