apiVersion: v1
kind: PersistentVolume
metadata:
  name: manman-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /tf_files
    server: 10.0.2.30


