apiVersion: v1
kind: Pod
metadata:
  name: manman-training
spec:
  restartPolicy: OnFailure
  containers:
    - name: manman-training
      image: 172.30.100.208:5000/manman/manman-training:latest
      imagePullPolicy: Always
      volumeMounts:
      - mountPath: "/tf_files"
        name: "manman-pv"
  volumes:
    - name: "manman-pv"
      persistentVolumeClaim:
        claimName: "nfs-claim"
